### ISSUE TITLE
Could you please provide some examples?

### ISSUE THREAD

**Issue by pahaz** [huaweicloud/huaweicloud-sdk-nodejs-v3#4]
You have examples here: https://github.com/huaweicloud/huaweicloud-sdk-nodejs-obs/tree/master/examples

It will help a lot if you create something similar for this repository

**Comment by akhuang** [comment]
You can try generating sample code online.

for example:  https://apiexplorer.developer.huaweicloud.com/apiexplorer/sdk?product=ECS&api=CreatePostPaidServers

![image](https://user-images.githubusercontent.com/1182708/152934744-5a473202-2e56-4208-93ef-684b2062e469.png)
