### ISSUE TITLE
FunctionGraph创建函数时，不支持部分runtime类型

### ISSUE THREAD

**Issue by xinwuyun** [huaweicloud/huaweicloud-sdk-nodejs-v3#5]
[文档](https://support.huaweicloud.com/api-functiongraph/functiongraph_06_0108.html#section3)中显示支持runtime如下

+ Python2.7
+ Python3.6
+ Go1.8
+ Go1.x
+ Java8
+ Node.js6.10
+ Node.js8.10
+ Node.js10.16
+ Node.js12.13
+ C#(.NET Core 2.0)
+ C#(.NET Core 2.1)
+ C#(.NET Core 3.1)
+ Custom
+ PHP7.3

源码中的枚举类型中只有如下

https://github.com/huaweicloud/huaweicloud-sdk-nodejs-v3/blob/d6b8970556edebf436241729f43e0453d710c69f/services/functiongraph/v2/model/CreateFunctionRequestBody.ts#L182-L194

**Comment by wangnengyuan** [comment]
sorry, sdk Missing Go1.x,wo will add it later.

**Comment by wangnengyuan** [comment]
sorry, sdk missing some runtime languages, we will add it later.

**Comment by xinwuyun** [comment]
> sorry, sdk missing some runtime languages, we will add it later.

Ok, thank you.
